"""empty message

Revision ID: 066807f82758
Revises: 4298f441ca43
Create Date: 2021-02-20 10:22:48.226389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066807f82758'
down_revision = '4298f441ca43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows_table',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    op.add_column('Artist', sa.Column('seeking_flag', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_flag')
    op.drop_column('Artist', 'seeking_flag')
    op.drop_table('shows_table')
    # ### end Alembic commands ###
